### ISSUE TITLE
No jobs found

### ISSUE THREAD

**Issue by sbotev** [spinlud/linkedin-jobs-scraper#22]
Half of the times I get no jobs found on exactly the same link/query, any thoughts why this happens?

  scraper:info Using LoggedOutRunStrategy +0ms
  scraper:info Setting chrome launch options {
  headless: true,
  args: [
    '--enable-automation',
    '--start-maximized',
    '--window-size=1472,828',
    '--lang=en-GB',
    '--no-sandbox',
    '--disable-setuid-sandbox',
    '--disable-dev-shm-usage',
    '--disable-gpu',
    '--disable-accelerated-2d-canvas',
    '--disable-setuid-sandbox',
    '--disable-dev-shm-usage',
    "--proxy-server='direct://",
    '--proxy-bypass-list=*',
    '--allow-running-insecure-content',
    '--disable-web-security',
    '--disable-client-side-phishing-detection',
    '--disable-notifications',
    '--mute-audio',
    '--lang=en-GB'
  ],
  defaultViewport: null,
  pipe: true,
  slowMo: 200
} +2ms
  scraper:info [][Worldwide] Starting new query: query="" location="Worldwide" +2s
  scraper:info [][Worldwide] Query options {
  locations: [ 'Worldwide' ],
  limit: 20,
  optimize: true,
  filters: {
    companyJobsUrl: 'https://www.linkedin.com/jobs/search/?geoId=92000000',
    relevance: 'DD'
  }
} +1ms
  scraper:info [][Worldwide] Opening https://www.linkedin.com/jobs/search?location=Worldwide&sortBy=DD&start=0 +3s
  scraper:info [][Worldwide] No jobs found, skip +7s
  
--------------------------------------------------------------
On some tries it works (same link/query): 

  scraper:info Using LoggedOutRunStrategy +0ms
  scraper:info Setting chrome launch options {
  headless: true,
  args: [
    '--enable-automation',
    '--start-maximized',
    '--window-size=1472,828',
    '--lang=en-GB',
    '--no-sandbox',
    '--disable-setuid-sandbox',
    '--disable-dev-shm-usage',
    '--disable-gpu',
    '--disable-accelerated-2d-canvas',
    '--disable-setuid-sandbox',
    '--disable-dev-shm-usage',
    "--proxy-server='direct://",
    '--proxy-bypass-list=*',
    '--allow-running-insecure-content',
    '--disable-web-security',
    '--disable-client-side-phishing-detection',
    '--disable-notifications',
    '--mute-audio',
    '--lang=en-GB'
  ],
  defaultViewport: null,
  pipe: true,
  slowMo: 200
} +1ms
  scraper:info [][Worldwide] Starting new query: query="" location="Worldwide" +2s
  scraper:info [][Worldwide] Query options {
  locations: [ 'Worldwide' ],
  limit: 20,
  optimize: true,
  filters: {
    companyJobsUrl: 'https://www.linkedin.com/jobs/search/?geoId=92000000',
    relevance: 'DD'
  }
} +0ms
  scraper:info [][Worldwide] Opening https://www.linkedin.com/jobs/search?location=Worldwide&sortBy=DD&start=0 +3s
  scraper:info [][Worldwide] Jobs fetched: 25 +3s

**Comment by spinlud** [comment]
Hi there!
It seems Linkedin randomly load different page versions of their frontend (no idea why). Please try latest version where I've added support for this different page version (I hope they won't add a third 😅 ) and see how it goes
