### ISSUE TITLE
mismatch results job title & description

### ISSUE THREAD

**Issue by jbdw85** [spinlud/linkedin-jobs-scraper#23]
Since last update and after the first 13 results or so, the jobtitle and company name do not match the description and link anymore.
Any idea how to fix?  in console.log with the events.scraper.data you can see it happening.

**Comment by spinlud** [comment]
Hi there, could you try latest version and see if it solves the issue?

**Comment by jbdw85** [comment]
Amazing, it works again! great work, thanks so much :)
