### ISSUE TITLE
Cant Extract: data.seniority_level, data.industries while using Authenticated strategy. 

### ISSUE THREAD

**Issue by tiagorestrepoe** [spinlud/linkedin-jobs-scraper#24]
Every time I run it in anonymous strategy i get always **seniority_level** and **industries** values, but when i try to use the library with Authenticated strategy i get nothing in those values.  I add the following code to the library to obtain the data 

```

lista_ = []
def on_data(data: EventData):

    jobs_data = [data.title, data.company,data.place, data.employment_type,data.seniority_level, data.link, data.job_function, data.industries, data.description ]

    lista_.append(jobs_data)
```

**Comment by Dyon42** [comment]
did you solved this issue because i ahve now the same issue
