### ISSUE TITLE
timeout error when I use valid cookies

### ISSUE THREAD

**Issue by yusuf963** [spinlud/linkedin-jobs-scraper#25]
Hi, I got    scraper:error [devops][France][1] Timeout on loading job details +0ms    every time I authenticate and use my cookies, 
so basically, the terminals log that session valid, but after it keeps erroring every 10s          Timeout on loading job details +0ms **Note: the script run fine in anonymous mood**
screenShot:

![Inkedcookies_LI](https://user-images.githubusercontent.com/58535314/126654432-c0455c04-526d-4697-99fc-ed326dc2e1f0.jpg)

**Comment by spinlud** [comment]
Hi, please try latest version
