### ISSUE TITLE
I keep getting an error even after setting the .env file with the LI_AT_COOKIE variable

### ISSUE THREAD

**Issue by calvinomiguel** [spinlud/linkedin-jobs-scraper#31]
Even after setting the `LI_AT_COOKIE` variable I keep getting this message. Anonymous session strategy is no longer maintained and it won't probably work. It is recommended to use an authenticated session, see documentation at https://github.com/spinlud/linkedin-jobs-scraper#anonymous-vs-authenticated-session. I'm not sure if I am placing the .env file in a wrong place. But is there a specific place where the file should be placed at? I'm placing it right at the root of the project. But is this correct? Thanks for help!

<img width="279" alt="image" src="https://user-images.githubusercontent.com/31018737/162587472-1061b104-b377-4868-bb2e-32785d5dfe9b.png">

**Comment by spinlud** [comment]
You should source your env file manually or use some package like https://www.npmjs.com/package/dotenv

**Comment by calvinomiguel** [comment]
> 

But where exactly should I source it, and what do you mean by sourcing an env file? As you can see, I have an env file in the root of my project.
