### ISSUE TITLE
Scrap company IMG url

### ISSUE THREAD

**Issue by calvinomiguel** [spinlud/linkedin-jobs-scraper#33]
This is not a bug, but a feature request. It' be great to be able to get the img of company's profile.

Thank you so much for this tool!

**Comment by calvinomiguel** [comment]
Unfortunatelly this one it's not working. the object property `companyImgLink` is returning nothing.

**Comment by calvinomiguel** [comment]
That's weird. Can you show me thw rest of your code?

**Comment by calvinomiguel** [comment]
I've reinstalled the setup 3 times already. Still no companyImg. Not sure what's going on. When I log the data object, there is no companyImgLink property to be seen. This is what I get:

<img width="1993" alt="grafik" src="https://user-images.githubusercontent.com/31018737/165705889-a49c4dea-c245-4394-88e8-955ffda37dee.png">

**Comment by spinlud** [comment]
Please make sure you are running with authenticated session (coookie set). Anonymous session is no longer supported.

This is a sample code I have just tested:

```js
const {
    LinkedinScraper,
    events,
} = require("linkedin-jobs-scraper");

(async () => {
    const scraper = new LinkedinScraper({
        headless: true,
        slowMo: 200,
        args: [
            "--lang=en-GB",
        ],
    });

    // Add listeners for scraper events
    scraper.on(events.scraper.data, (data) => {
        console.log(
            `Id='${data.jobId}'`,
            `Title='${data.title}'`,
            `Place='${data.place}'`,
            `Company='${data.company ? data.company : "N/A"}'`,
            `Location='${data.location}'`,
            `Link='${data.link}'`,
            `CompanyLink='${data.companyLink ? data.companyLink : "N/A"}'`,
            `CompanyImgLink='${data.companyImgLink ? data.companyImgLink : "N/A"}'`,
        );
        console.log('------------------------------------------------------------------------------');
    });

    await Promise.all([
        scraper.run([
            {
                query: "Engineer",
                options: {
                    limit: 10,
                    optimize: false,
                    locations: ["United States"],
                }
            }
        ])
    ]);

    await scraper.close();
})();
```

![image](https://user-images.githubusercontent.com/12783208/165711675-27d5d0d2-fa8e-4149-973a-caa72c59952d.png)

**Comment by calvinomiguel** [comment]
I'm pretty sure, I am using a cookie, but I'll try later again. Thanks for the clue ;-)
