### ISSUE TITLE
How to extract the salary range?

### ISSUE THREAD

**Issue by giulioambrogi** [spinlud/linkedin-jobs-scraper#34]
Hello, 

Is there a way to extract the salary range? Or is the feature in the plans at all?

Thanks

**Comment by spinlud** [comment]
Hi there,
salary range is not always available. You can find additional job info (including salary range) in the insights field, which is a (potentially empty) array of strings. The following are some examples:

['Full-time']
['Full-time · Executive', '10,001+ employees · Financial Services', 'Actively recruiting']
['$117,000/yr - $199,000/yr (LinkedIn est.) · Full-time · Executive', '10,001+ employees · Oil and Gas', 'Actively recruiting']
['Full-time', '51-200 employees', '🎨 Payman Taei is hiring for this job', 'Actively recruiting']
['Full-time · Mid-Senior level', '11-50 employees · Internet Publishing', 'Actively recruiting']
['Full-time', '5,001-10,000 employees · IT Services and IT Consulting', 'Actively recruiting']

**Comment by giulioambrogi** [comment]
Ok thank you
