### ISSUE TITLE
"No jobs found, skip" with all queries.

### ISSUE THREAD

**Issue by igncampa** [spinlud/linkedin-jobs-scraper#39]
npm -v 8.15.0
chromium Version 103.0.5060.134 (Official Build) snap (64-bit)

The scraper returns `No jobs found, skip` every time regardless of keywords, locations, parameters, etc.

Any idea what's going on? I'm having issues with the python version too, although a different error.

edit just to note the above happens while using the `LI_AT_COOKIE`

**Comment by spinlud** [comment]
Hi, it seems related to an html element that has changed css class. Should be fixed now
