### ISSUE TITLE
Search by company

### ISSUE THREAD

**Issue by anthonytison** [spinlud/linkedin-jobs-scraper#4]
Hi,

Thanks for this great plugin. It's very useful. 
However, could you allow users to search jobs for a company ?

**Comment by spinlud** [comment]
Hi!
You can just use the name of the company as your job query:

![image](https://user-images.githubusercontent.com/12783208/79052122-79b0e080-7c34-11ea-9271-1fe63f891dc5.png)

For example you can use `Google` as the job query to search for Google jobs:

```js
scraper.run(
    "Google",
    "United States",
    {
        paginationMax: 2,
    }
)
```

Hope this helps!

**Comment by anthonytison** [comment]
Hi!! Thx for your answer.
