### ISSUE TITLE
Add time filter

### ISSUE THREAD

**Issue by safaiyeh** [spinlud/linkedin-jobs-scraper#9]
![Screen Shot 2020-07-20 at 6 48 20 PM](https://user-images.githubusercontent.com/8675043/88003386-96717580-cab9-11ea-9ee1-a8d3392788d1.png)

Is it possible to set the search to "Past 24 hrs"

**Comment by spinlud** [comment]
Actually no, but it is possible to add. As soon as I have time

**Comment by safaiyeh** [comment]
Thanks @spinlud would be a great addition, appreciate your work here.

**Comment by DanielGarciaGuillen** [comment]
I would like this too. Also @spinlud  is there anyway to buy you a coffee?

**Comment by spinlud** [comment]
Here you go guys, I've just added filters for relevance and time in `v2.2.1`. I've also added `typescript` support if you like. Let me know how it goes!

**Comment by safaiyeh** [comment]
I appreciate it! I'll check it out sometime this week. This is awesome thanks!
